# Generated by Django 2.2.7 on 2019-11-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_datecheck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateCheck',
            new_name='Date_check',
        ),
        migrations.AlterModelOptions(
            name='date_check',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='date_check',
            old_name='date_top30',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='column',
            name='date',
        ),
        migrations.CreateModel(
            name='Column_top30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns_top30', to='kanban.Board')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_top30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('market', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_top30', to='kanban.Column')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
