# Generated by Django 2.2.7 on 2019-11-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_auto_20191125_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_top30',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_top30', to='kanban.Board'),
        ),
    ]
